services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_STRAPI_TOKEN: ${NEXT_PUBLIC_STRAPI_TOKEN}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    restart: always
    ports:
      - 3001:3000
    networks:
      - ventodoro

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
      args:
        DATABASE_CLIENT: ${DATABASE_CLIENT}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        NODE_ENV: production
    environment:
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
    volumes:
      - ./backend/public/uploads:/opt/app/public/uploads
    depends_on:
      - database
    restart: always
    ports:
      - 1338:1337
    networks:
      - ventodoro

  # caddy:
  #   image: caddy:alpine
  #   container_name: caddy
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - ./caddy/data:/data
  #     - ./caddy/config:/config
  #   networks:
  #     - ventodoro

  database:
    image: postgres:17.4
    shm_size: 1gb
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    networks:
      - ventodoro
    volumes:
      - ./psql/data:/var/lib/postgresql/data
    restart: always

networks:
  ventodoro:
    external: true
    name: ventodoro

secrets:
  postgres-passwd:
    environment: DATABASE_PASSWORD
